[package]
name = "magic-loc-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "0.2.*"
heapless = { version = "0.7.14", default-features = false }
array-init = "2.1.0"
bilge = { package = "bilge", git = "https://github.com/hecatia-elegua/bilge" }
